
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
      <div>
          <h1>Login</h1>
          {children}
      </div>
  );
}
